# ==========================================================================
# CONFIGURACION DEL SERVIDOR SPRING BOOT
# ==========================================================================
server.port=8080
server.servlet.context-path=/

# ==========================================================================
# BASE DE DATOS: MICROSOFT SQL SERVER
# ==========================================================================
spring.datasource.url=jdbc:sqlserver://IP:PORT;databaseName=EduPortalDB;trustServerCertificate=true;encrypt=false
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
# POR SEGURIDAD NO COLOCO LOS DATOS Y ACCESO A LA BASE DE DATOS
spring.datasource.username=USUARIO
spring.datasource.password=CONTRASEÑA

# ==========================================================================
# CONFIGURACION JPA / HIBERNATE
# ==========================================================================
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# ==========================================================================
# SEGURIDAD Y TOKEN JWT
# ==========================================================================
app.jwt.secret=9a3f2c4e6b8a1d5f7e9c2b4a6f8d0e1c3a5b7d9e1f3a5c7e9b1d3f5a7c9e1b3d
app.jwt.expiration-ms=86400000

# ==========================================================================
# LOGGING
# ==========================================================================
logging.level.com.idat.eduportal=INFO
logging.level.org.springframework.security=WARN
